services:
  postgres-local:
    restart: always
    image: 'postgres:17'
    container_name: postgres-local
    ports:
      - '4002:5432'
    volumes:
      - './docker/postgresql:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres.password
      - POSTGRES_DB=diver
